import CAR_SIZE_TYPE from './CAR_SIZE_TYPE';

const CAR_TYPE_SEGMENT = {
  C: CAR_SIZE_TYPE.SMALL_SIZE,
  D: CAR_SIZE_TYPE.MIDDLE_SIZE,
  E: CAR_SIZE_TYPE.BIG_SIZE,
  SUV: CAR_SIZE_TYPE.SUV
};

export default CAR_TYPE_SEGMENT;
